const advisors: [string, string, string, string, string, string][] = [
    [
        'Saira Anwar',
        'https://engineering.tamu.edu/mtde/profiles/anwar-saira.html',
        'Engineering and computing education research, educational technologies, instrument design, data science, cognitive and noncognitive factors',
        'Department of Multidisciplinary Engineering',
        'Texas A & M University',
        'USA',
    ],
    [
        'Syedah Zahra Atiq',
        'https://cse.osu.edu/people/atiq.2',
        'Non-cognitive factors, broadening participation',
        'Computer Science and Engineering',
        'The Ohio State University',
        'USA',
    ],
    [
        'Erik Barendsen*',
        'https://www.ru.nl/english/people/barendsen-e/',
        'pedagogy, literacy, computational thinking',
        'Science Education',
        'Radboud University',
        'Netherlands',
    ],
    [
        'Tiffany Barnes',
        'http://www4.ncsu.edu/~tmbarnes/',
        'inclusion, educational games, tutoring systems, teacher education',
        'Computer Science',
        'North Carolina State University',
        'USA',
    ],
    [
        'Austin Cory Bart',
        'https://acbart.github.io/',
        'introductory computing, motivation',
        'Computer Science',
        'University of Delaware',
        'USA',
    ],
    [
        'Brett Becker',
        'http://www.brettbecker.com',
        'novices, programming, compilers, errors',
        'Computer Science',
        'University College Dublin',
        'Ireland',
    ],
    [
        'Tim Bell',
        'http://www.cosc.canterbury.ac.nz/tim.bell/',
        'CS unplugged, curriculum',
        'Computer Science',
        'University of Canterbury',
        'New Zealand',
    ],
    [
        'Marc Berges*',
        'https://www.ddi.tf.fau.de/personen/leitung/berges/',
        'PCK and programming education',
        'Department of Computer Science',
        'Universitaet Erlangen-Nuernberg',
        'Germany',
    ],
    [
        'Anders Berglund*',
        'https://katalog.uu.se/profile/?id=XX3048',
        'CS education',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Matthew Berland*',
        'http://berland.org/',
        'digital media, data science learning',
        'Curriculum & Instruction, Computer Science',
        'University of Wisconsin-Madison',
        'USA',
    ],
    [
        'Paulo Blikstein*',
        'https://www.tc.columbia.edu/faculty/pb2755/',
        'project-based learning',
        'Communications, Media and Learning Technology Design',
        'Columbia University',
        'USA',
    ],
    [
        'Kristy Boyer*',
        'http://research.csc.ncsu.edu/learndialogue/person.php?id=keboyer',
        'intelligent tutoring systems',
        'Computer Science',
        'University of Florida',
        'USA',
    ],
    [
        'Karen Brennan',
        'https://www.gse.harvard.edu/faculty/karen-brennan',
        'constructionism, creativity, K-12 classrooms, teacher learning',
        'Graduate School of Education',
        'Harvard',
        'USA',
    ],
    [
        'Jed Brubaker',
        'https://www.colorado.edu/cmci/people/information-science/jed-brubaker',
        'how identity is designed, represented and experienced in socio-technical systems',
        'Information Science',
        'University of Colorado, Boulder',
        'USA',
    ],
    [
        'Åsa Cajander*',
        'https://katalog.uu.se/profile/?id=N2-392',
        'learning and didactics',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Cornelia Connolly',
        'http://www.nuigalway.ie/our-research/people/education/corneliaconnolly/',
        'pedagogy, teacher education, computational thinking, design',
        'School of Education',
        'National University of Ireland, Galway',
        'Ireland',
    ],
    [
        'Steve Cooper*',
        'http://cse.unl.edu/~scooper/',
        'program visualization, spatial reasoning',
        'Computer Science & Engineering',
        'University of Nebraska, Lincoln',
        'USA',
    ],
    [
        'Katie Cunningham',
        'https://www.kicunningham.com',
        'programming plans, novel learning environmemts, conversational programmers',
        'Computer Science',
        'University of Illinois Urbana-Champaign',
        'USA',
    ],
    [
        'Quintin Cutts*',
        'http://www.dcs.gla.ac.uk/~quintin/',
        'pedagogy, assessment, work based learning and teacher learning communities',
        'School of Computer Science',
        'University of Glasgow',
        'Scotland',
    ],
    [
        'Mats Daniels*',
        'https://katalog.uu.se/profile/?id=XX3066',
        'computing and engineering education research, group projects',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Joshua Danish*',
        'https://education.indiana.edu/about/directory/profiles/danish-joshua-a.html',
        'how people learn through activity',
        'School of Education',
        'Indiana University Bloomington',
        'USA',
    ],
    [
        'Sayamindu Dasgupta*',
        'https://unmad.in/',
        'youth, data science',
        'School of Information and Library Science',
        'University of North Carolina at Chapel Hill',
        'USA',
    ],
    [
        'Adrienne Decker',
        'https://adriennedecker.net/',
        'pedagogy, assessment, efficacy of outreach',
        'Engineering Education',
        'University at Buffalo',
        'USA',
    ],
    [
        'Paul Denny',
        'https://www.cs.auckland.ac.nz/~paul/',
        'collaborative learning, online learning, gamification, student-generated resources',
        'Computer Science',
        'University of Auckland',
        'New Zealand',
    ],
    [
        'Kayla DesPortes*',
        'https://steinhardt.nyu.edu/faculty/Kayla_Desportes',
        'computing as a medium for expression',
        'Learning Sciences',
        'New York University',
        'USA',
    ],
    [
        'Sebastian Dziallas*',
        'http://sdziallas.com/',
        'experiences in higher education CS',
        '',
        'Fulbright University Vietnam',
        'Vietnam',
    ],
    [
        'Betsy DiSalvo*',
        'http://betsydisalvo.com/',
        'culture, informal learning',
        'School of Interactive Computing',
        'Georgia Tech',
        'USA',
    ],
    [
        'Brian Dorn*',
        'http://faculty.ist.unomaha.edu/bdorn/',
        'HCI, informal learning, teacher education',
        'Department of Computer Science',
        'University of Nebraska, Omaha',
        'USA',
    ],
    [
        'Anna Eckerdal*',
        'https://katalog.uu.se/profile/?id=N99-802',
        'threshold concepts, MOOCs, learning in labs',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Steve Edwards*',
        'http://webcore.cs.vt.edu/user/edwards',
        'software engineering, formal methods, autograding',
        'Computer Science',
        'Virginia Tech',
        'USA',
    ],
    [
        'Barbara Ericson*',
        'http://barbara-ericson.strikingly.com/',
        'pedagogy, diversity',
        'School of Information',
        'University of Michigan',
        'USA',
    ],
    [
        'Martin Erwig',
        'http://web.engr.oregonstate.edu/~erwig/',
        'programming languages, visual languages, explanations, story programming',
        'Electrical Engineering and Computer Science',
        'Oregon State University',
        'USA',
    ],
    [
        'Marisa Exter',
        'https://www.education.purdue.edu/faculty-profiles/name/marisa-exter/',
        'post secondary, lifelong learning, interdisciplinarity, competency-based education',
        'Department of Curriculum & Instruction',
        'Purdue University',
        'USA',
    ],
    [
        'Katrina Falkner*',
        'http://www.adelaide.edu.au/directory/katrina.falkner',
        'pedagogy, computational thinking',
        'School of Computer Science',
        'University of Adelaide',
        'Australia',
    ],
    [
        'Casey Fiesler*',
        'https://www.colorado.edu/cmci/people/information-science/casey-fiesler',
        'technology ethics',
        'Information Science',
        'University of Colorado, Boulder',
        'USA',
    ],
    [
        'Kathi Fisler',
        'http://web.cs.wpi.edu/~kfisler/',
        'Programming languages, pedagogy, cross-disciplinary learning and transfer',
        'Computer Science',
        'Brown University',
        'USA',
    ],
    [
        'Diana Franklin',
        'http://people.cs.uchicago.edu/~dmfranklin/',
        'Equity, curriculum, and CS learning in K-8',
        'Department of Computer Science',
        'University of Chicago',
        'USA',
    ],
    [
        'Armando Fox*',
        'https://www2.eecs.berkeley.edu/Faculty/Homepages/fox.html',
        'digital learning, programming systems, and software engineering',
        'Electrical Engineering & Computer Science',
        'University of California, Berkeley',
        'USA',
    ],
    [
        'Christina Gardner-McCune*',
        'https://www.cise.ufl.edu/gardner-mccune-christina/',
        'Computer Science Education, AI Education, Design of Learning Technologies & Learning Environments, Curriculum Development & Assessment, K-12 Computing After-School & Summer Camps, Learning Sciences',
        'Computer & Information Science & Engineering',
        'University of Florida',
        'USA',
    ],
    [
        'Joanna Goode*',
        'https://education.uoregon.edu/people/faculty/goodej',
        'Access and equity for underrepresented students of color and females in computer science education',
        'College of Education',
        'University of Oregon',
        'USA',
    ],
    [
        'Jeff Grey',
        'http://gray.cs.ua.edu',
        'Block-based languages',
        'Department of Computer Science',
        'University of Alabama',
        'USA',
    ],
    [
        'Bill Griswold',
        'https://cseweb.ucsd.edu/~wgg/',
        'HCI, software engineering education, and educational tools',
        'Department of Computer Science & Engineering',
        'University of California, San Diego',
        'USA',
    ],
    [
        'Tovi Grossman',
        'http://www.tovigrossman.com/',
        'HCI, software learning, interactive tutorials',
        'Computer Science',
        'University of Toronto',
        'Canada',
    ],
    [
        'Philip Guo',
        'http://www.pgbovine.net/',
        'HCI, learning at scale',
        'Cognitive Science',
        'University of California, San Diego',
        'USA',
    ],
    [
        'Mark Guzdial*',
        'http://www.cc.gatech.edu/home/guzdial/',
        'pedagogy, curriculum, end-user programming, teachers, research instruments, theory',
        'Computer Science & Engineering, Engineering Education Research',
        'University of Michigan',
        'USA',
    ],
    [
        'Sarah Heckman',
        'https://people.engr.ncsu.edu/sesmith5/',
        'software engineering, automated grading, and help-seeking',
        'Computer Science',
        'North Carolina State University',
        'USA',
    ],
    [
        'Geoffrey Herman',
        'http://publish.illinois.edu/glherman/',
        'conceptual change and student learning, assessment and measurement, pedagogy, and faculty development',
        'Computer Science',
        'University of Illinois, Urbana-Champaign',
        'USA',
    ],
    [
        'Felienne Hermans',
        'http://www.felienne.com/',
        'K-12 education, misconceptions, teacher education, direct instruction, end-user programming',
        'Computer Science',
        'Leiden University',
        'The Netherlands',
    ],
    [
        'Nathan Holbert',
        'https://www.tc.columbia.edu/faculty/nrh2118/',
        'constructionism, diversity',
        'Mathematic Science and Technology, Teachers College',
        'Columbia University',
        'USA',
    ],
    [
        'Chris Hundhausen',
        'http://www.eecs.wsu.edu/~hundhaus/',
        'social learning technologies and pedagogical approaches',
        'Computer Science',
        'Washington State University',
        'USA',
    ],
    [
        'Sridhar Iyer*',
        'https://www.it.iitb.ac.in/~sri/',
        'computing education research',
        'Computer Science and Engineering',
        'Indian Institute of Technology Bombay',
        'India',
    ],
    [
        'Yasmin Kafai',
        'http://scholar.gse.upenn.edu/kafai',
        'constructionism, educational games, electronic textiles, Scratch',
        'Graduate School of Education',
        'University of Pennsylvania',
        'USA',
    ],
    [
        'Dennis Kafura*',
        'https://people.cs.vt.edu/kafura/',
        'computational thinking',
        'Computer Science',
        'Virginia Tech',
        'USA',
    ],
    [
        'Caitlin Kelleher*',
        'http://www.cse.wustl.edu/~ckelleher/',
        'learning technology',
        'Computer Science',
        'Washington University in St. Louis',
        'USA',
    ],
    [
        'Scott Klemmer*',
        'http://d.ucsd.edu/srk/',
        'HCI, learning at scale',
        'Cognitive Science',
        'University of California, San Diego',
        'USA',
    ],
    [
        'Stephan Krusche',
        'http://www.skrusche.de/',
        'Education technologies, in particular in learning platforms, assessment, learning analytics and adaptive learning',
        'School of Computation',
        'Technical University of Munich',
        'Germany',
    ],
    [
        'Amy J. Ko',
        'http://faculty.uw.edu/ajko/',
        'Critical computing education, programming language learning, pre-service teacher education',
        'The Information School, Computer Science & Engineering',
        'University of Washington, Seattle',
        'USA',
    ],
    [
        'Michael Kölling*',
        'https://nms.kcl.ac.uk/michael.kolling/',
        'computing education',
        'Faculty of Natural and Mathematical Sciences',
        "King's College London",
        'UK',
    ],
    [
        'Shriram Krishnamurthi*',
        'https://cs.brown.edu/~sk/',
        'programming languages, pedagogy',
        'Computer Science',
        'Brown University',
        'USA',
    ],
    [
        'Celine Latulipe*',
        'https://celinelatulipe.wordpress.com/',
        'HCI, creativity, pedagogy',
        'Software and Information Systems',
        'UNC Charlotte',
        'USA',
    ],
    [
        'Michael J. Lee',
        'http://pixel42.com/',
        'HCI, educational games, diversity, learning technologies',
        'Informatics',
        'New Jersey Institute of Technology',
        'USA',
    ],
    [
        'Victor Lee',
        'http://victor-r-lee.com/',
        'learning sciences, computational thinking with board games, early childhood computational thinking, maker education',
        'Graduate School of Education',
        'Stanford University',
        'USA',
    ],
    [
        'Leen-kiat Soh',
        'https://cse.unl.edu/~lksoh/',
        'multiagent systems, computer science education, and intelligent data analytics',
        'Computer Science and Engineering',
        'University of Nebraska, Lincoln',
        'USA',
    ],
    [
        'Colleen Lewis',
        'https://cs.illinois.edu/directory/profile/colleenl',
        'Understanding and optimizing learning; identifying and removing barriers',
        'Computer Science',
        'University of Illinois at Urbana-Champaign',
        'USA',
    ],
    [
        'Raymond Lister*',
        'http://www.uts.edu.au/staff/raymond.lister',
        'cognition, assessment, program understanding',
        'School of Software',
        'University of Technology, Sydney',
        'Australia',
    ],
    [
        'Lukas Z. Liu',
        'https://web.edu.hku.hk/faculty-academics/lukasliu',
        'Computational thinking, Learning analytics, Game-based learning',
        'Faculty of Education',
        'University of Hong Kong',
        'Hong Kong',
    ],
    [
        'Dastyni Loksa*',
        'http://students.washington.edu/dloksa/#/',
        'Programming problem solving',
        'Computer & Information Sciences',
        'Towson University',
        'USA',
    ],
    [
        'Andrew Luxton-Reilly*',
        'https://unidirectory.auckland.ac.nz/profile/alux001',
        'learning communities, game-based learning, debugging, automated assessment, gender and diversity in CS',
        'Computer Science',
        'University of Auckland',
        'New Zealand',
    ],
    [
        'Alejandra J. Magana',
        'https://polytechnic.purdue.edu/profile/admagana',
        'Computational thinking, model-based reasoning, cyberlearning, discipline-based computing education',
        'Computer and Information Technology and Engineering Education',
        'Purdue University',
        'USA',
    ],
    [
        'Lauri Malmi',
        'http://www.cs.hut.fi/~lma/',
        'program visualization, algorithm visualization, automatic assessment',
        'Computer Science',
        'Aalto University',
        'Finland',
    ],
    [
        'Lauren Margulieux*',
        'https://laurenmarg.com/',
        'online learning in computing',
        'Department of Learning Sciences',
        'Georgia State University',
        'USA',
    ],
    [
        'Eva Marinus',
        'https://www.phsz.ch/ausbildung/dozierende/eva-marinus/',
        'cognition, assessment, misconceptions',
        ' Institute for Media and School',
        'Schwyz University of Teacher Education',
        'Switzerland',
    ],
    [
        'Briana Morrison*',
        'http://www.brianamorrison.net/',
        'pedagogy, cognitive load',
        'Computer Science',
        'University of Virginia',
        'USA',
    ],
    [
        'Lijun Ni',
        'https://www.albany.edu/education/faculty/lijun-ni',
        'K-12 computer science education, teacher education and  professional development',
        'Department of Educational Theory and Practice',
        'University at Albany, State University of New York',
        'USA',
    ],
    [
        'Lars-Åke Nordén*',
        'https://katalog.uu.se/profile/?id=N3-976',
        'self-efficacy',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Aletta Nylén*',
        'https://www.it.uu.se/katalog/aletta',
        'STEM and computing education',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Chris Orban*',
        'https://physics.osu.edu/people/orban.14',
        'high school physics and math CS integration',
        'Physics',
        'The Ohio State University',
        'USA',
    ],
    [
        "Eleanor O'Rourke",
        'http://www.eleanorourke.com/',
        'HCI, educational games, learning technology, growth mindset, motivation',
        'Computer Science and Learning Science',
        'Northwestern',
        'USA',
    ],
    [
        'Tapan Parikh',
        'http://tap2k.org/',
        'Data science, civic tech, equity',
        'School of Information',
        'Cornell Tech',
        'USA',
    ],
    [
        'Elizabeth Patitsas',
        'http://www.cs.mcgill.ca/~patitsas/',
        'Computing as literacy, educational/technical inequity, sociology of education, gender studies, disability studies, teacher development, educator practices, policy analysis, computing & society, science and technology studies (STS), diversity',
        'School of Computer Science, Department of Integrated Studies in Education',
        'McGill University',
        'Canada',
    ],
    [
        'Jamie Payton*',
        'https://cis.temple.edu/~payton/',
        'Broadening participation in computing, and evidence-based approaches to improving computer science education',
        'Computer and Information Sciences',
        'Temple University',
        'USA',
    ],
    [
        'Roy Pea*',
        'http://web.stanford.edu/~roypea/',
        'learning science, informal learning',
        'Education and Learning Sciences',
        'Stanford',
        'USA',
    ],
    [
        'Arnold Pears*',
        'http://www.it.uu.se/katalog/arnoldp',
        'pedagogy',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Bill Penuel*',
        'https://www.colorado.edu/education/william-penuel',
        'teacher learning and organizational processes',
        'Education',
        'University of Colorado, Boulder',
        'USA',
    ],
    [
        'Anne-Kathrin Peters*',
        'https://katalog.uu.se/profile/?id=N11-1467',
        'sustainability education, identities, norms, values',
        'Department of Information Technology',
        'Uppsala University',
        'Sweden',
    ],
    [
        'Marian Petre*',
        'http://mcs.open.ac.uk/mp8/',
        'software design, design pedagogy',
        'Centre for Research in Computing',
        'The Open University',
        'UK',
    ],
    [
        'Leo Porter',
        'https://cseweb.ucsd.edu/~leporter/',
        'pedagogy, assessment, educational data mining',
        'Computer Science and Engineering',
        'University of California, San Diego',
        'USA',
    ],
    [
        'Joël Porquet-Lupine',
        'https://luplab.cs.ucdavis.edu/',
        'curriculum development for teaching introductory programming courses, educational tools',
        'Computer Science',
        'University of California, Davis',
        'USA',
    ],
    [
        'Thomas Price',
        'https://people.engr.ncsu.edu/twprice/website/',
        'educational data mining, tutoring systems, automated feedback',
        'Computer Science',
        'North Carolina State&nbsp;University',
        'USA',
    ],
    [
        'Keith Quille',
        'http://keithquille.com/',
        'pedagogy, introductory programming, educational data mining, predicting success, CS1, K-12',
        'Department of Computing',
        'TU Dublin, Tallaght Campus',
        'Ireland',
    ],
    [
        'Gerald Soosai Raj',
        'https://adalbertgerald.github.io',
        'Making computing more accessible to diverse learners (e.g., Non-native English Speakers)',
        'Computer Science and Engineering',
        'University of California, San Diego',
        'USA',
    ],
    [
        'Mitch Resnick*',
        'http://web.media.mit.edu/~mres/',
        'constructionism, creativity',
        'Media Lab',
        'MIT',
        'USA',
    ],
    [
        'Judy Robertson*',
        'https://www.ed.ac.uk/profile/judy-robertson',
        'data science education, curriculum development, teacher professional learning and games-based learning',
        'School of Education',
        'The University of Edinburgh',
        'Scotland',
    ],
    [
        'Anthony Robins',
        'http://www.cs.otago.ac.nz/staff/Anthony_Robins',
        'psychology of programming, language learning, first programming language, novice programmers, CS1',
        'Computer Science',
        'University of Otago',
        'New Zealand',
    ],
    [
        'Ricarose Roque',
        'http://www.ricarose.com/',
        'constructionism, creativity, informal learning, family learning',
        'Information Science',
        'CU Boulder',
        'USA',
    ],
    [
        'Monique Ross*',
        'https://www.moniqueross.com/',
        'broadening participation, with a focus on computer science',
        'Computing and Information Science',
        'Florida International University',
        'USA',
    ],
    [
        'Linda Sax*',
        'https://gseis.ucla.edu/directory/linda-sax/',
        'diversity in undergraduate CS and STEM',
        'Department of Education',
        'University of California, Los Angeles',
        'USA',
    ],
    [
        'Sue Sentance*',
        'https://www.cst.cam.ac.uk/people/ss2600',
        'computing education',
        'Computer Science education',
        'University of Cambridge',
        'UK',
    ],
    [
        'Cliff Shaffer*',
        'http://people.cs.vt.edu/shaffer/',
        'digital education',
        'Computer Science',
        'Virginia Tech',
        'USA',
    ],
    [
        'Kristin Searle*',
        'https://itls.usu.edu/people/faculty/searle/',
        'gender, culture, engagement with computing',
        'Instructional Technology and Learning Sciences',
        'Utah State University',
        'USA',
    ],
    [
        'Carsten Schulte*',
        'http://www.uni-paderborn.de/person/60311/',
        'pedagogy',
        'Computer Science',
        'Paderborn University',
        'Germany',
    ],
    [
        'Valerie Shute*',
        'http://myweb.fsu.edu/vshute/',
        'assessment',
        'Education',
        'Florida State University',
        'USA',
    ],
    [
        'Ben Shapiro*',
        'http://benshapi.ro/',
        'constructionism, new media',
        'ATLAS Institute, Computer Science',
        'University of Colorado',
        'USA',
    ],
    [
        'Andreas Stefik',
        'http://web.cs.unlv.edu/stefika/',
        'Human factors of programming language design, accessibility',
        'Computer Science',
        'University of Nevada, Las Vegas',
        'USA',
    ],
    [
        'Jakita O. Thomas',
        'https://www.jakitaothomas.com',
        'computational algorithmic thinking, intersectional computing, complex cognitive skill development, computer-supported collaborative learning',
        'Computer Science and Software Engineering',
        'Auburn University',
        'USA',
    ],
    [
        'Frank Vahid',
        'https://www.cs.ucr.edu/~vahid',
        'College-level CS ed',
        'Computer Science and Engineering',
        'University of California, Riverside',
        'USA',
    ],
    [
        'Jan Vahrenhold',
        'https://www.uni-muenster.de/Informatik.AGVahrenhold/personen/prof.dr.janvahrenhold/',
        'algorithms, non-cognitive factors, TA education',
        'Computer Science',
        'University of Münster',
        'Germany',
    ],
    [
        'Sepehr Vakil',
        'https://sites.northwestern.edu/sepehrvakil/',
        'sociocultural perspectives on learning and identity; ethics and politics of computing; social justice education',
        'Learning Sciences',
        'Northwestern University',
        'USA',
    ],
    [
        'Erin Walker',
        'http://faculty.engineering.asu.edu/ewalker/',
        'personalized learning environments, computer-supported collaborative learning, robotic learning environments',
        'School of Computing and Information',
        'University of Pittsburgh',
        'USA',
    ],
    [
        'David Weintrop',
        'http://www.terpconnect.umd.edu/~weintrop',
        'design of learning environments, computational thinking, K-12 Classrooms',
        'College of Education & College of Information Studies',
        'University of Maryland',
        'USA',
    ],
    [
        'Uri Wilensky*',
        'http://ccl.northwestern.edu/Uri.shtml',
        'computational thinking, science integration',
        'Learning Sciences',
        'Northwestern University',
        'USA',
    ],
    [
        'Michelle Wilkerson',
        'https://www.ocf.berkeley.edu/~mwilkers/',
        'Computing in K-12 science and math education; w/ focus on modeling and data',
        'Graduate School of Education',
        'UC Berkeley',
        'USA',
    ],
    [
        'Joseph Jay Williams',
        'http://www.josephjaywilliams.com/',
        'HCI, A/B experimentation, learnersourcing, personalization, multi-armed bandits/reinforcement learning, self-explanation, metacognition, motivation and social psychology interventions, cognitive science, mental health, learning at scale',
        'Computer Science',
        'University of Toronto',
        'Canada',
    ],
    [
        'Gary K. W. Wong',
        'https://web.edu.hku.hk/faculty-academics/wongkwg',
        'Computational thinking, Computer science education, Artificial intelligence education',
        'Faculty of Education',
        'University of Hong Kong',
        'Hong Kong',
    ],
    [
        'Aman Yadav',
        'http://www.amanyadav.org/',
        'computational thinking, teacher education, problem-based learning, teacher professional development',
        'Educational Psychology and Educational Technology',
        'Michigan State University',
        'USA',
    ],
    [
        'Mark Zarb',
        'https://rgu-repository.worktribe.com/person/77298/mark-zarb',
        'Computing Education, Pedagogy, Teaching and Learning, Transitions into HE, Student Resilience, Post-Pandemic Educational Landscapes',
        'School of Computing',
        'Robert Gordon University',
        'Scotland',
    ],
    [
        'Haoqi Zhang*',
        'http://users.eecs.northwestern.edu/~hq/',
        'learning ecosystems',
        'Computer Science',
        'Northwestern',
        'USA',
    ],
];

export default advisors;
