import type { Source } from '../../data/Sources';
import type { Paper } from '../../data/Pubs';
import type { Person } from '../../data/People';
import type { Post } from '../../data/Posts';
import type { Impact } from '../../data/Impact';
import type { Degree } from '../../data/Degrees';
import type { Patent } from '../../data/Patents';
import type { Job } from '../../data/Jobs';
import type { Recognition } from '../../data/Recognitions';
import type { Editing } from '../../data/EditingRoles';
import type { Reviewing } from '../../data/ReviewingRoles';
import type { DoctoralCommittee } from '../../data/DoctoralCommittees';
import type { Funding } from '../../data/Funding';
import type { TravelInfo } from '../../data/Travel';
import type { Service } from '../../data/ServiceRoles';
import type { Talk } from '../../data/Talks';
import type { Class } from '../../data/Classes';
import type { CommitmentDetails } from '../../data/Commitments';
import type { Panel } from '../../data/Panels';
import type { Discovery } from '../../data/Discoveries';
import type { DiscoveryID } from '../../data/Discoveries';

type ProfileSpec = {
    announcement: string | undefined;
    sources: Record<string, Source>;
    pubs: Paper[];
    people: readonly Person[];
    discoveries: Record<DiscoveryID, Discovery>;
    impacts: Impact[];
    degrees: Degree[];
    patents: Patent[];
    jobs: Job[];
    recognitions: Recognition[];
    editing: Editing[];
    reviewing: Reviewing[];
    doctoralCommittees: DoctoralCommittee[];
    funding: Funding[];
    posts: Post[];
    travel: TravelInfo[];
    service: Service[];
    talks: Talk[];
    classes: Class[];
    panels: Panel[];
    commitments: CommitmentDetails[];
    years: Record<string, string | null>;
};

export type { ProfileSpec as default };
